services:
    dockerimage:
        container_name: boersdata-raw
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "5004:5004"
            - "5104:5104"
        env_file:
            - .env
        networks:
            - boersdata-infra
        restart: unless-stopped

networks:
    boersdata-infra:
        name: masterdata-network
        external: true