services:
    securities-masterdata:
        container_name: securities-masterdata-1
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "5001:5001"
            - "5101:5101"
        networks:
            - masterdata
        env_file:
            - .env
        restart: unless-stopped

#    securities-masterdata-2:
#        container_name: securities-masterdata-2
#        build:
#            context: .
#            dockerfile: ./Dockerfile
#        networks:
#            - masterdata
#        env_file:
#            - .env
#        restart: unless-stopped
#
#    securities-masterdata:
#        image: nginx:alpine
#        ports:
#            - "5001:5001"
#            - "5101:5101"
#        volumes:
#            - ./nginx.conf:/etc/nginx/nginx.conf:ro
#        networks:
#            - masterdata
#        depends_on:
#            - securities-masterdata-1
#            - securities-masterdata-2
#        restart: unless-stopped

networks:
    masterdata:
        name: masterdata-network