events {
    worker_connections 1024;
}

http {
    upstream securities_masterdata_backend {
        server securities-masterdata-1:5001;
        server securities-masterdata-2:5001;
    }

    server {
        listen 5001;
        
        location / {
            proxy_pass http://securities_masterdata_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

stream {
    upstream securities_masterdata_grpc {
        server securities-masterdata-1:5101;
        server securities-masterdata-2:5101;
    }

    server {
        listen 5101;
        proxy_pass securities_masterdata_grpc;
    }
}