using System.Data;
using FluentMigrator;

namespace article_news_raw.Migrations;

/// <summary>
/// Baseline of the tables that existed before this service had any migrations. They were created
/// out-of-band, so both are guarded by an existence check: a no-op against the live database, but
/// it lets a fresh database be provisioned from code. Mirrors <c>ArticleNewsDbContext.OnModelCreating</c>.
/// </summary>
[Migration(20260816_1200)]
public class BaselineArticleTables : ForwardOnlyMigration
{
    public override void Up()
    {
        if (!Schema.Table("article_url").Exists())
        {
            Create.Table("article_url")
                .WithColumn("id").AsInt32().Identity().PrimaryKey()
                .WithColumn("url").AsString(Int32.MaxValue).NotNullable()
                // Npgsql maps DateTime to "timestamp with time zone", which AsDateTime() would not give us.
                .WithColumn("date_url_fetched").AsCustom("timestamp with time zone").NotNullable()
                .WithDefault(SystemMethods.CurrentDateTime)
                .WithColumn("date_article_published").AsCustom("timestamp with time zone").Nullable()
                .WithColumn("is_content_read").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("is_parsed").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("is_bad").AsBoolean().NotNullable().WithDefaultValue(false);

            // Identity() gives us GENERATED ALWAYS, the DbContext declares UseIdentityByDefaultColumn().
            Execute.Sql("ALTER TABLE article_url ALTER COLUMN id SET GENERATED BY DEFAULT;");
        }

        if (!Schema.Table("article_ticker_sentiment").Exists())
        {
            Create.Table("article_ticker_sentiment")
                .WithColumn("id").AsInt32().Identity().PrimaryKey()
                .WithColumn("article_url_id").AsInt32().NotNullable()
                .WithColumn("ticker").AsString(Int32.MaxValue).NotNullable()
                .WithColumn("sentiment_score").AsDouble().NotNullable()
                .WithColumn("relevance_score").AsDouble().NotNullable();

            Create.ForeignKey("TICKER_SENTIMENT_HAS_ARTICLE_URL")
                .FromTable("article_ticker_sentiment").ForeignColumn("article_url_id")
                .ToTable("article_url").PrimaryColumn("id")
                .OnDelete(Rule.Cascade);

            Execute.Sql("ALTER TABLE article_ticker_sentiment ALTER COLUMN id SET GENERATED BY DEFAULT;");
        }
    }
}
