<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ttm_system.Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Utils\" />
    </ItemGroup>

</Project>
